In [1]:
#1
import numpy as np
a= np.array([1,2,3])# tạo mảng 1 chiều
print(type(a)) #in ra kiểu dữ liệu a
print(a.shape) #in ra kích thước của mảng
print(a[0], a[1],a[2]) #in ra phần tử tại vị trí 0 1 2 trong a
a[0]=5 # thay vị trí dầu tiên trong mảng a =5
print(a) # in ra a

b=np.array([[1,2,3],[4,5,6]]) # tạo mảng 2 chiều
print(b.shape) # in kích thước của mảng
print(b[0,0], b[0,1], b[1,0]) # in ra phần tử nằm tại những vị trí (hàng ,cột)



<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [7]:
# 2
import numpy as np
a=np.zeros((2,2))# tạo 2 hàng 2 cột all sô 0
b=np.ones((1,2))# tạo 1 hàng 2 cột all số 1
c=np.full((2,2),7)# tạo 2 hàng 2 cột all sô 7
d=np.eye(2) #tạo 2 hàng 2 cột 
e=np.random.random((2,2)) # tạo 2 hàng 2 cột sô random
print("a=",a)
print("b=",b)
print("c=",c)
print("d=",d)
print("e=",e)

a= [[0. 0.]
 [0. 0.]]
b= [[1. 1.]]
c= [[7 7]
 [7 7]]
d= [[1. 0.]
 [0. 1.]]
e= [[0.02952648 0.39724256]
 [0.20018634 0.30251116]]


In [9]:
#3
import  numpy as np
a= np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])# tạo mảng 3 hàng 4 cột 
b= a[:2,1:3] # hàng từ 0 tới 1 cột từ 1 tới 2
print(a[0,1]) #in phần tử hàng 0 cột 1
b[0,0]=77 # thay đổi giá trị tại hàng 0 cột 0 là 77
print(a[0,1]) # in phần tử tại hàng 0 cột 1

2
77


In [14]:
#4
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]) # tạo mảng 3x4
row_r1 = a[1, :] # lấy hàng 1 cột in hết  dạng 1D (4,)
row_r2 = a[1:2, :]  # lấy hàng 1 cột in hết dạng 2D (1,4)
print(row_r1, row_r1.shape)  #in mảng row_r1 và kích thước
print(row_r2, row_r2.shape)   #in mảng row_r2 và kích thước
col_r1 = a[:, 1]# lấy tất cả hàng cột 1 dạng  1 D
col_r2 = a[:, 1:2] # lấy tất cả hàng cột 1 dạng  2D
print(col_r1, col_r1.shape)   #in mảng row_r1 và kích thước
print(col_r2, col_r2.shape)   #in mảng row_r2 và kích thước


[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [15]:
#5
import numpy as np
a = np.array([[1,2], [3, 4], [5, 6]]) # tạo mảng 3X2
print(a[[0, 1, 2], [0, 1, 0]]) # lấy phần tử tại vị trí [0,0] [1,1] [2,0]
print(np.array([a[0, 0], a[1, 1], a[2, 0]])) # in ra phần tử tại vị trí [0,0] [1,1] [2,0] nhưng theo cách khác với cái trên
print(a[[0, 0], [1, 1]]) #  lấy phần tử tại vị trí [0,1] [0,1]
print(np.array([a[0, 1], a[0, 1]])) # cũng y như trên nhưng theo cách khác gọn hơn


[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [16]:
#6
import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])# tạo mảng 4x3
print(a) # in mảng a 
b = np.array([0, 2, 0, 1]) # lấy giá trị tại vị trí theo thứ tự từ 0 tới 3 
                            # hàng 0 → cột 0
                            # hàng 1 → cột 2
                            # hàng 2 → cột 0
                            # hàng 3 → cột 
print(a[np.arange(4), b]) # a[np.arange(4), b] truy cập các phần tử (0,0), (1,2), (2,0), (3,1)
                            # np.arange(4) tạo ra [0, 1, 2, 3]
a[np.arange(4), b] += 10 # tăng mỗi phần tử trong (0,0), (1,2), (2,0), (3,1) lên 10
print(a) # in ra sau khi tăng những phần tử trong (0,0), (1,2), (2,0), (3,1) lên 10


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [17]:
#7
import numpy as np
a = np.array([[1,2], [3, 4], [5, 6]]) # tạo mảng 3x2
bool_idx = (a > 2) # phần tử nào trong a >2  thì true còn lại false
print(bool_idx) # in  ra true hay false để biết phần tử nào <2 
print(a[bool_idx]) # in ra các phần tử >2 
print(a[a > 2]) # cũng là y như trên nhưng cách khác 


[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [23]:
# 8
import numpy as np
x = np.array([1, 2]) # tạo mảng sô nguyên
print(x.dtype) # in kiểu dữ liệu của mảng

x = np.array([1.0, 2.0]) # tạo mảng số float
print(x.dtype) # in kiểu dữ liệu của mảng

x = np.array([1, 2], dtype=np.int64) # ép kiểu dữ liệu sang int64
print(x.dtype) # in kiểu dữ liệu của mảng


int64
float64
int64


In [24]:
# 9
import numpy as np
x = np.array([[1,2],[3,4]], dtype=np.float64) # tạo mảng 2x2 theo kiểu dữ liệu float
y = np.array([[5,6],[7,8]], dtype=np.float64) # tạo mảng 2x2 theo kiểu dữ liệu float

print(x + y) # cộng từ phần tử với nhau 
print(np.add(x, y)) # cũng cộng phần tử với nhau mà cách khác
print(x - y)# trừ phần tử với nhau
print(np.subtract(x, y)) # cũng trừ phần tử với nhau mà cách khác
print(x * y) # nhân phần tử với nhau
print(np.multiply(x, y))  # cũng nhân phần tử với nhau mà cách khác
print(x / y) # chia phần tử với nhau
print(np.divide(x, y))# cũng chia phần tử với nhau mà cách khác
print(np.sqrt(x)) # căn bậc 2 từng phẩn tử của x


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [25]:
# 9
import numpy as np
x = np.array([[1,2],[3,4]]) # tạo mảng 2x2
y = np.array([[5,6],[7,8]]) # tạo mảng 2x2
v = np.array([9,10]) # tạo mảng  1chiều
w = np.array([11, 12]) #tạo mảng 1 chiều

print(v.dot(w))# tích vô hướng của 2 vector
print(np.dot(v, w)) # cũng là tích vô hướng của 2 vector 
print(x.dot(v)) # ma trận x nhân vector v → vector mới
print(np.dot(x, v))# giống dòng trên
print(x.dot(y)) # tích ma trận x nhân y 
print(np.dot(x, y))# giống dòng trên


219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [26]:
# 10
import numpy as np
x = np.array([[1,2],[3,4]]) # tạo mảng 2x2
print(np.sum(x)) # tỉnh tổng lại hết phần tử trong mảng
print(np.sum(x, axis=0)) # tính tổng theo từng cột
print(np.sum(x, axis=1)) # tính tổng theo từng hàng

x = np.array([[1,2], [3,4]])# tạo mảng 2x2
print(x) # in mảng x
print(x.T) # đảo hàng thành cột

v = np.array([1,2,3]) # tạo mảng 1 chiều
print(v) # in mảng v
print(v.T) # đảo thứ tự cột  nhưng chỉ có 1 cột nên nên vẫn như cũ


10
[4 6]
[3 7]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [28]:
# 11
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]) # tạo mảng 4x3
v = np.array([1, 0, 1]) # tạo mảng 1 chiều
y = np.empty_like(x)# tạo một mảng rổng y có cùng kích thước với x

for i in range(4): # vòng for lặp lại 4 lần
    y[i, :] = x[i, :] + v # cộng  vector v với từng phần tử trong x

print(y)# in mảng y ra


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [33]:
# 12
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]) # tạo mảng 4x3
v = np.array([1, 0, 1]) #tạo mảng 1 chiều
vv = np.tile(v, (4, 1)) # lặp lại 4 lần [1,0,1]  tạo ra 4 hàng với cột thì y như v
print(vv)

y = x + vv# cộng từng phần tử của x và vv lại với nhau do chúng có cùng kích thước mảng 4x3
print(y)


[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [34]:
# 13
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]]) # tạo mảng 4x3
v = np.array([1, 0, 1])# tạo mảng 1 chiều
y = x + v # cộng x và v lại với nhau được vì v có cùng số cột với mảng x nên v sẽ cộng hết vào từng hàng 
print(y)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [36]:
# 14
import numpy as np

v = np.array([1,2,3]) # tạo mảng 1 chiều
w = np.array([4,5]) # toạ mảng 1 chiều

print(np.reshape(v, (3, 1)) * w)# reshape(v, (3,1)) biến v thành ma trận 3x1\
# [[1],
#  [2],
#  [3]]
# ma trận 3x1 nhân với vector 1x2  tạo ma trận 3x2
x = np.array([[1,2,3], [4,5,6]]) # tạo mảng 2x3
print(x + v) # cộng từng phần tử vào mảng 
print((x.T + w).T) # x đảo chiều hàng thành cột thành 3x2 ta có cột là 2 rồi nên việt w cộng được là hợp lệ rồi sao đó đảo  ngược nó lại 
print(x + np.reshape(w, (2, 1))) # reshape(w, (2,1)) biến w thành ma trận 2x1 
# [[4],
# [5]] 
# vậy nên cộng x vào w hợp lệ do w đã đổi thành mảng 2x1

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]


In [37]:
# 15
import numpy as np
v = np.array([1,2,3])# tạo mảng 1 chiều
w = np.array([4,5]) # tạo mảng 1 chiều

print(np.reshape(v, (3, 1)) * w)# reshape(v, (3,1)) biến v thành ma trận 3x1
# [[1],
#  [2],
#  [3]]
x = np.array([[1,2,3], [4,5,6]])# tạo mảng 2x3
print(x + v) # cộng mảng x với v lại
print((x.T + w).T) # đảo hàng thành cột của mảng x lai biến mảng x thành 
print(x + np.reshape(w, (2, 1)))
print(x * 2)


[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]
